name: Sync i18n Translations

on:
  workflow_dispatch:
#  push:
#    branches:
#      - develop
#    paths:
#      - frontend/src/i18n/*.json
#  schedule:
#    - cron: 0 17 * * 5 # Fridays around 5pm

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: i18n
  cancel-in-progress: false

jobs:
  crowdin:
    name: Synchronize with Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@9c23991700c0ec5256fd41089b9d9d7d540e424e # v3.3.0
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: chore/-/sync-translations

          create_pull_request: true
          commit_message: 'chore(i18n): sync translations from crowdin'
          pull_request_title: 'chore(i18n): sync translations from crowdin'
          pull_request_body: >
            ## Description

            updates the i18n files from crowdin automatically
          pull_request_base_branch_name: develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
